# Generated by Django 4.2.6 on 2024-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_populer',
            field=models.BooleanField(default=True),
        ),
    ]
