# Generated by Django 4.2.6 on 2024-04-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_is_populer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='electric_product',
        ),
    ]
