# Generated by Django 4.2.6 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_product',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
    ]
