# Generated by Django 4.2.6 on 2024-05-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_electric_product_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('about_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('tech_image', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('tech_title', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_description', models.TextField(blank=True, null=True)),
                ('camera_image', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('camera_title', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_description', models.TextField(blank=True, null=True)),
                ('technology_image', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('technology_title', models.CharField(blank=True, max_length=50, null=True)),
                ('technology_description', models.TextField(blank=True, null=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='cimg')),
                ('design_title', models.CharField(blank=True, max_length=50, null=True)),
                ('design_description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catagory')),
                ('electric_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.electric_product')),
            ],
        ),
        migrations.DeleteModel(
            name='product_detail',
        ),
    ]
