# Generated by Django 4.2.6 on 2024-05-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_productdetail_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_galary',
            old_name='elect_product',
            new_name='electproduct',
        ),
    ]
