# Generated by Django 4.2.6 on 2024-05-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_productdetail_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
                ('electproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.electric_product')),
            ],
        ),
    ]
